window.RESTAURANTS = [
  { "name": "フードホリディ", "genre": ["ヘルシー"], "healthy_score": 5, "price_score": 3, "taste_score": 4 },
  { "name": "のすた", "genre": ["ラーメン"], "healthy_score": 1, "price_score": 4, "taste_score": 4 },
  { "name": "ゆきもり", "genre": ["和食"], "healthy_score": 4, "price_score": 3, "taste_score": 4 },
  { "name": "あむん", "genre": ["スパニッシュ"], "healthy_score": 3, "price_score": 3, "taste_score": 4 },
  { "name": "焔", "genre": ["和食"], "healthy_score": 2, "price_score": 5, "taste_score": 4 },
  { "name": "ニッコロガシ", "genre": ["和食"], "healthy_score": 3, "price_score": 4, "taste_score": 4 },
  { "name": "由良鼎", "genre": ["ラーメン", "和食"], "healthy_score": 3, "price_score": 3, "taste_score": 5 },
  { "name": "由良", "genre": ["和食"], "healthy_score": 4, "price_score": 2, "taste_score": 5 },
  { "name": "やまかわ", "genre": ["和食"], "healthy_score": 4, "price_score": 4, "taste_score": 4 },
  { "name": "土筆", "genre": ["和食"], "healthy_score": 4, "price_score": 5, "taste_score": 4 },
  { "name": "ジンディンロウ", "genre": ["中華"], "healthy_score": 2, "price_score": 3, "taste_score": 4 },
  { "name": "ウィズグリーン", "genre": ["ヘルシー"], "healthy_score": 5, "price_score": 3, "taste_score": 3 },
  { "name": "チャッピーノ", "genre": ["イタリアン"], "healthy_score": 3, "price_score": 3, "taste_score": 4 },
  { "name": "イタリアン食堂MAS parte oimachi", "genre": ["イタリアン"], "healthy_score": 3, "price_score": 3, "taste_score": 4 },
  { "name": "Mare & Oyster 大井町トラックス店", "genre": ["洋食"], "healthy_score": 4, "price_score": 2, "taste_score": 4 },
  { "name": "大元", "genre": ["中華"], "healthy_score": 2, "price_score": 5, "taste_score": 5 },
  { "name": "萬来園", "genre": ["中華"], "healthy_score": 2, "price_score": 3, "taste_score": 5 },
  { "name": "広州市場 大井町トラックス店", "genre": ["ラーメン", "中華"], "healthy_score": 2, "price_score": 4, "taste_score": 4 },
  { "name": "ロジウラカリィ サムライ. OIMACHI TRACKS", "genre": ["エスニック"], "healthy_score": 3, "price_score": 2, "taste_score": 4 },
  { "name": "スパイスカレーとおやつ Curia Lente", "genre": ["エスニック"], "healthy_score": 3, "price_score": 3, "taste_score": 5 },
  { "name": "七宝麻辣湯 大井町店", "genre": ["中華", "エスニック"], "healthy_score": 3, "price_score": 3, "taste_score": 5 },
  { "name": "KEIKI BEACH 83", "genre": ["エスニック", "ヘルシー", "寿司"], "healthy_score": 4, "price_score": 3, "taste_score": 3 },
  { "name": "ADO KEBAB HOUSE 大井町店", "genre": ["エスニック"], "healthy_score": 3, "price_score": 4, "taste_score": 3 },
  { "name": "いきなりステーキ", "genre": ["洋食"], "healthy_score": 2, "price_score": 3, "taste_score": 3 },
  { "name": "うまい鮨勘 大井町支店", "genre": ["和食"], "healthy_score": 4, "price_score": 2, "taste_score": 5 },
  { "name": "くら寿司 イトーヨーカドー大井町店", "genre": ["和食"], "healthy_score": 4, "price_score": 4, "taste_score": 3 },
  { "name": "富士そば", "genre": ["そば"], "healthy_score": 4, "price_score": 5, "taste_score": 3 },
  { "name": "渋そば", "genre": ["そば"], "healthy_score": 3, "price_score": 5, "taste_score": 3 },
  { "name": "そば道", "genre": ["そば"], "healthy_score": 3, "price_score": 3, "taste_score": 4 },
  { "name": "吉野家", "genre": ["和食"], "healthy_score": 2, "price_score": 5, "taste_score": 3 },
  { "name": "サイゼリヤ", "genre": ["イタリアン"], "healthy_score": 2, "price_score": 5, "taste_score": 3 },
  { "name": "HinataCafe", "genre": ["洋食"], "healthy_score": 3, "price_score": 3, "taste_score": 4 },
  { "name": "茶豆珈琲", "genre": ["洋食"], "healthy_score": 3, "price_score": 3, "taste_score": 3 },
  { "name": "アンクルJr.", "genre": ["洋食", "エスニック"], "healthy_score": 2, "price_score": 3, "taste_score": 4 },
  { "name": "大戸屋", "genre": ["和食"], "healthy_score": 4, "price_score": 4, "taste_score": 4 },
  { "name": "洋麺屋五右衛門", "genre": ["イタリアン"], "healthy_score": 4, "price_score": 3, "taste_score": 4 },
  { "name": "伊達の牛たん本舗 大井町トラックス店", "genre": ["和食", "牛タン"], "healthy_score": 3, "price_score": 2, "taste_score": 4 },
  { "name": "どうとんぼり神座", "genre": ["ラーメン"], "healthy_score": 2, "price_score": 4, "taste_score": 3 },
  { "name": "つけめん維新", "genre": ["ラーメン"], "healthy_score": 1, "price_score": 3, "taste_score": 4 },
  { "name": "時知らず", "genre": ["ラーメン"], "healthy_score": 2, "price_score": 3, "taste_score": 4 },
  { "name": "まる", "genre": ["ラーメン"], "healthy_score": 2, "price_score": 3, "taste_score": 5 },
  { "name": "酒場ゆいと", "genre": ["和食"], "healthy_score": 4, "price_score": 3, "taste_score": 5 },
  { "name": "とんかつ あおき", "genre": ["とんかつ"], "healthy_score": 1, "price_score": 2, "taste_score": 5 },
  { "name": "おうちごはん", "genre": ["和食"], "healthy_score": 4, "price_score": 3, "taste_score": 4 },
  { "name": "山本のハンバーグ", "genre": ["洋食"], "healthy_score": 2, "price_score": 3, "taste_score": 4 },
  { "name": "シズラー", "genre": ["洋食"], "healthy_score": 4, "price_score": 1, "taste_score": 5 },
  { "name": "イェロー", "genre": ["洋食"], "healthy_score": 1, "price_score": 3, "taste_score": 4 }
];
